# Generated by Django 4.1.3 on 2022-12-06 14:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_product_options_alter_service_options_and_more'),
        ('contacts', '0003_rename_ser_id_servicecontact_car_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcontact',
            options={'verbose_name': 'Product Contact', 'verbose_name_plural': 'Product Contacts'},
        ),
        migrations.AlterModelOptions(
            name='servicecontact',
            options={'verbose_name': 'Human Resource Contact', 'verbose_name_plural': 'Human Resource Contacts'},
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='car_id',
            field=models.IntegerField(verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='car_title',
            field=models.CharField(max_length=100, verbose_name='car title'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='customer_need',
            field=models.CharField(max_length=100, verbose_name='customer need'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='firs tname'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='productcontact',
            name='user_id',
            field=models.IntegerField(blank=True, verbose_name='user id'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.service', verbose_name='human resource id'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='car_title',
            field=models.CharField(max_length=100, verbose_name='service title'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='customer_need',
            field=models.CharField(max_length=100, verbose_name='customer need'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='firs tname'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='message',
            field=models.TextField(blank=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='user_id',
            field=models.IntegerField(blank=True, verbose_name='user id'),
        ),
    ]
