# Generated by Django 4.1.3 on 2022-12-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_productcontact_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecontact',
            old_name='car_id',
            new_name='ser_id',
        ),
    ]
