# Generated by Django 4.1.3 on 2022-12-06 14:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_productcatagory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-created',), 'verbose_name': 'Human Resource', 'verbose_name_plural': 'Human Resources'},
        ),
        migrations.AlterField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.productcatagory', verbose_name='catagory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_avilable',
            field=models.BooleanField(default=True, verbose_name='is_avilable'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is_verified'),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Gondar', 'Gondar'), ('Dessie', 'Dessie'), ('Bahirdar', 'Bahirdar'), ('Semera', 'Semera')], max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pics',
            field=models.ImageField(upload_to='pro_pics/%Y/%m/%d/', verbose_name='product_picture'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_pics1',
            field=models.FileField(upload_to='pro_pics/%Y/%m/%d/', verbose_name='product_picture1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='service',
            name='catagory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.servicecatagory', verbose_name='catagory'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='experiance',
            field=models.PositiveSmallIntegerField(verbose_name='experiance'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_avilable',
            field=models.BooleanField(default=True, verbose_name='is_avilable'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='is_verified'),
        ),
        migrations.AlterField(
            model_name='service',
            name='location',
            field=models.CharField(choices=[('Addis Ababa', 'Addis Ababa'), ('Gondar', 'Gondar'), ('Dessie', 'Dessie'), ('Bahirdar', 'Bahirdar'), ('Semera', 'Semera')], max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_pics',
            field=models.ImageField(upload_to='pro_pics/%Y/%m/%d/', verbose_name='service_picture'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_pics1',
            field=models.FileField(upload_to='pro_pics/%Y/%m/%d/', verbose_name='service_picture'),
        ),
        migrations.AlterField(
            model_name='service',
            name='skill',
            field=models.CharField(max_length=1000, verbose_name='skill'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
