# Generated by Django 4.1.3 on 2022-12-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcatagory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Products Category'},
        ),
        migrations.AlterModelOptions(
            name='servicecatagory',
            options={'verbose_name': 'Human Resource Category', 'verbose_name_plural': 'Human Resources Categories'},
        ),
        migrations.AlterField(
            model_name='productcatagory',
            name='catagory',
            field=models.CharField(max_length=70, verbose_name='catagory'),
        ),
        migrations.AlterField(
            model_name='servicecatagory',
            name='catagory',
            field=models.CharField(max_length=70, verbose_name='catagory'),
        ),
    ]
