# Generated by Django 4.1.3 on 2022-12-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_productcatagory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatagory',
            name='catagory_image',
            field=models.ImageField(default='static/car/car-3.jpg', upload_to='category_pic/%Y/%m/%d/', verbose_name='category_picture'),
        ),
        migrations.AddField(
            model_name='servicecatagory',
            name='catagory_image',
            field=models.ImageField(default='static/car/car-3.jpg', upload_to='category_pic/%Y/%m/%d/', verbose_name='category_picture'),
        ),
    ]
