# Generated by Django 4.1.3 on 2022-12-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_productcatagory_catagory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatagory',
            name='catagory_image',
            field=models.ImageField(upload_to='category_pic/%Y/%m/%d/', verbose_name='category_picture'),
        ),
        migrations.AlterField(
            model_name='servicecatagory',
            name='catagory_image',
            field=models.ImageField(upload_to='category_pic/%Y/%m/%d/', verbose_name='category_picture'),
        ),
    ]
